-- Relaciones documentales entre ADC y bolsas GVA.
-- Migración aditiva e idempotente.

CREATE TABLE IF NOT EXISTS adc_bolsas_relacionadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adc_proceso_id BIGINT NOT NULL,
    referencia_bolsa TEXT NOT NULL,
    bolsa_proceso_id BIGINT,
    evidencia TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_adc_bolsas_relacionadas_adc_referencia
        UNIQUE (adc_proceso_id, referencia_bolsa),
    CONSTRAINT fk_adc_bolsas_relacionadas_adc
        FOREIGN KEY (adc_proceso_id) REFERENCES procesos(id),
    CONSTRAINT fk_adc_bolsas_relacionadas_bolsa
        FOREIGN KEY (bolsa_proceso_id) REFERENCES procesos(id)
);

CREATE INDEX IF NOT EXISTS idx_adc_bolsas_relacionadas_referencia
    ON adc_bolsas_relacionadas(referencia_bolsa);

CREATE INDEX IF NOT EXISTS idx_adc_bolsas_relacionadas_bolsa_proceso
    ON adc_bolsas_relacionadas(bolsa_proceso_id);
