-- TuCoach Empleo · 004 · Trazabilidad y exclusión mutua del ciclo periódico.
--
-- Resuelve tres problemas del cron anterior:
--   1. Nada impedía que un reintento lanzara un segundo ciclo mientras el
--      primero seguía en marcha (no había ningún lock).
--   2. Un fallo de una fuente no dejaba rastro: la ventana de lectura era
--      siempre de 7 días, así que tras una caída larga los cierres publicados
--      mientras tanto se perdían para siempre.
--   3. El cron respondía "verde" aunque todas las fuentes hubieran fallado.
--
-- Idempotente: se puede ejecutar varias veces.

CREATE TABLE IF NOT EXISTS ciclos_periodicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    fin TIMESTAMPTZ,
    estado TEXT NOT NULL DEFAULT 'EN_CURSO'
        CHECK (estado IN ('EN_CURSO', 'OK', 'CON_ERRORES', 'ABANDONADO')),
    historico BOOLEAN NOT NULL DEFAULT FALSE,
    resumen JSONB
);

-- Como mucho UN ciclo en curso a la vez. Se usa un índice único parcial y no
-- pg_advisory_lock porque los advisory locks de sesión no son fiables con el
-- pooler en modo transacción de Supabase (puerto 6543).
CREATE UNIQUE INDEX IF NOT EXISTS uq_ciclo_en_curso
    ON ciclos_periodicos ((TRUE))
    WHERE estado = 'EN_CURSO';

CREATE TABLE IF NOT EXISTS ejecuciones_fuente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciclo_id BIGINT REFERENCES ciclos_periodicos(id) ON DELETE CASCADE,
    fuente TEXT NOT NULL,
    estado TEXT NOT NULL,            -- OK | SIN_NOVEDADES | DEGRADADA | ERROR
    inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duracion_s NUMERIC,
    hasta_fecha DATE,                -- último día cubierto por la ventana leída
    dias_ventana INTEGER,
    error TEXT
);

-- Para calcular "último éxito por fuente" sin recorrer el histórico.
CREATE INDEX IF NOT EXISTS idx_ejecuciones_fuente_exito
    ON ejecuciones_fuente (fuente, hasta_fecha DESC)
    WHERE estado IN ('OK', 'SIN_NOVEDADES');

-- Tablas internas: solo el backend (rol propietario) debe acceder. Sin
-- políticas, un cliente con la clave pública de Supabase no puede leerlas ni
-- escribirlas. (Conviene hacer lo mismo con el resto de tablas de empleo.)
ALTER TABLE ciclos_periodicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE ejecuciones_fuente ENABLE ROW LEVEL SECURITY;
