-- TuCoach Empleo
-- Esquema canónico de la BD independiente de Empleo.
-- La tabla procesos es la entidad central; publicaciones documenta fuentes;
-- cambios conserva trazabilidad; suscripciones/notificaciones cubren alertas.
-- oportunidades_activas es la interfaz SQL canónica para el catálogo público.

CREATE TABLE organismos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    provincia TEXT,
    municipio TEXT,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_organismos_nombre_tipo UNIQUE (nombre, tipo)
);

CREATE TABLE fuentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organismo_id BIGINT,
    nombre TEXT NOT NULL,
    tipo TEXT NOT NULL,
    url TEXT NOT NULL,
    prioridad INTEGER NOT NULL DEFAULT 100,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (organismo_id) REFERENCES organismos(id)
);

CREATE UNIQUE INDEX uq_fuentes_organismo_url ON fuentes(organismo_id, url);

CREATE TABLE procesos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organismo_id BIGINT NOT NULL,
    codigo_externo TEXT,
    identificador_estable TEXT NOT NULL UNIQUE,
    denominacion TEXT NOT NULL,
    cuerpo_escala TEXT,
    grupo TEXT,
    subgrupo TEXT,
    tipo_proceso TEXT,
    sistema_selectivo TEXT,
    turno TEXT,
    plazas INTEGER,
    estado TEXT NOT NULL DEFAULT 'EN_SEGUIMIENTO',
    anio_oep INTEGER,
    anio_convocatoria INTEGER,
    fecha_convocatoria DATE,
    fecha_apertura DATE,
    fecha_cierre DATE,
    fecha_examen TIMESTAMPTZ,
    lugar_examen TEXT,
    ultima_publicacion_at TIMESTAMPTZ,
    fuente_principal_id BIGINT,
    datos_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    es_oportunidad BOOLEAN NOT NULL DEFAULT TRUE,
    origen_dato TEXT NOT NULL DEFAULT 'AUTOMATICO',
    revision_estado TEXT NOT NULL DEFAULT 'PUBLICADA',
    revisado_at TIMESTAMPTZ,
    revisado_por UUID,
    observaciones_internas TEXT,
    ambito_administrativo TEXT NOT NULL DEFAULT 'REVISION'
        CHECK (ambito_administrativo IN ('SI','NO','REVISION')),
    coaching_convocatoria_id BIGINT,
    coaching_disponible BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (organismo_id) REFERENCES organismos(id),
    FOREIGN KEY (fuente_principal_id) REFERENCES fuentes(id)
);

CREATE INDEX idx_procesos_organismo ON procesos(organismo_id);
CREATE INDEX idx_procesos_estado ON procesos(estado);
CREATE INDEX idx_procesos_oportunidad ON procesos(es_oportunidad);
CREATE INDEX idx_procesos_ambito_administrativo ON procesos(ambito_administrativo);
CREATE INDEX idx_procesos_anio_convocatoria ON procesos(anio_convocatoria);
CREATE INDEX idx_procesos_fecha_cierre ON procesos(fecha_cierre);
CREATE INDEX idx_procesos_origen_dato ON procesos(origen_dato);
CREATE INDEX idx_procesos_revision_estado ON procesos(revision_estado);
CREATE INDEX idx_procesos_coaching_disponible ON procesos(coaching_disponible);

CREATE TABLE publicaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    fuente_id BIGINT NOT NULL,
    referencia TEXT,
    tipo TEXT NOT NULL,
    titulo TEXT,
    fecha_publicacion DATE,
    url TEXT NOT NULL,
    contenido_hash TEXT,
    contenido_texto TEXT,
    datos_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    detectada_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON DELETE CASCADE,
    FOREIGN KEY (fuente_id) REFERENCES fuentes(id)
);

CREATE INDEX idx_publicaciones_proceso ON publicaciones(proceso_id);
CREATE INDEX idx_publicaciones_fecha ON publicaciones(fecha_publicacion);
CREATE UNIQUE INDEX uq_publicaciones_fuente_ref_url
    ON publicaciones(fuente_id, referencia, url);

CREATE TABLE cambios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    publicacion_id BIGINT,
    tipo TEXT NOT NULL,
    campo TEXT,
    valor_anterior TEXT,
    valor_nuevo TEXT,
    resumen TEXT NOT NULL,
    significativo BOOLEAN NOT NULL DEFAULT TRUE,
    detectado_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON DELETE CASCADE,
    FOREIGN KEY (publicacion_id) REFERENCES publicaciones(id) ON DELETE SET NULL
);

CREATE INDEX idx_cambios_proceso ON cambios(proceso_id);
CREATE INDEX idx_cambios_significativo ON cambios(significativo);

CREATE TABLE suscripciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    proceso_id BIGINT NOT NULL,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, proceso_id),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON DELETE CASCADE
);

CREATE INDEX idx_suscripciones_user ON suscripciones(user_id, activa);
CREATE INDEX idx_suscripciones_proceso ON suscripciones(proceso_id, activa);

CREATE TABLE notificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suscripcion_id BIGINT NOT NULL,
    cambio_id BIGINT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE',
    enviado_at TIMESTAMPTZ,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(suscripcion_id, cambio_id),
    FOREIGN KEY (suscripcion_id) REFERENCES suscripciones(id) ON DELETE CASCADE,
    FOREIGN KEY (cambio_id) REFERENCES cambios(id) ON DELETE CASCADE
);

CREATE INDEX idx_notificaciones_pendientes ON notificaciones(estado, created_at);

CREATE TABLE seguimiento_estado_usuario (
    user_id UUID PRIMARY KEY,
    ultima_novedad_vista_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE temarios_empleo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL UNIQUE,
    contenido_texto TEXT NOT NULL DEFAULT '',
    origen TEXT NOT NULL DEFAULT 'MANUAL',
    estado TEXT NOT NULL DEFAULT 'PENDIENTE_REVISION',
    fuente_publicacion_id BIGINT,
    fuente_url TEXT,
    fecha_extraccion TIMESTAMPTZ,
    revisado_at TIMESTAMPTZ,
    revisado_por UUID,
    observaciones TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON DELETE CASCADE,
    FOREIGN KEY (fuente_publicacion_id) REFERENCES publicaciones(id) ON DELETE SET NULL
);

CREATE TABLE temas_empleo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temario_id BIGINT NOT NULL,
    numero INTEGER,
    titulo TEXT,
    contenido_texto TEXT NOT NULL,
    orden INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (temario_id) REFERENCES temarios_empleo(id) ON DELETE CASCADE,
    UNIQUE(temario_id, orden)
);

CREATE INDEX idx_temas_empleo_temario ON temas_empleo(temario_id);

CREATE TABLE empleo_eventos_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proceso_id BIGINT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo = 'NUEVA_OPORTUNIDAD'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(proceso_id, tipo),
    FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON DELETE CASCADE
);

CREATE INDEX idx_empleo_eventos_notificacion_proceso
    ON empleo_eventos_notificacion(proceso_id);

CREATE TABLE empleo_envios_notificacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    email TEXT NOT NULL,
    estado TEXT NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE','ENVIADA','ERROR')),
    proveedor_message_id TEXT,
    enviado_at TIMESTAMPTZ,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(evento_id, user_id),
    FOREIGN KEY (evento_id) REFERENCES empleo_eventos_notificacion(id) ON DELETE CASCADE
);

CREATE INDEX idx_empleo_envios_notificacion_pendientes
    ON empleo_envios_notificacion(estado, created_at);

CREATE TABLE adc_bolsas_relacionadas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adc_proceso_id BIGINT NOT NULL,
    referencia_bolsa TEXT NOT NULL,
    bolsa_proceso_id BIGINT,
    evidencia TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(adc_proceso_id, referencia_bolsa),
    FOREIGN KEY (adc_proceso_id) REFERENCES procesos(id) ON DELETE CASCADE,
    FOREIGN KEY (bolsa_proceso_id) REFERENCES procesos(id) ON DELETE SET NULL
);

CREATE INDEX idx_adc_bolsas_relacionadas_referencia
    ON adc_bolsas_relacionadas(referencia_bolsa);
CREATE INDEX idx_adc_bolsas_relacionadas_bolsa_proceso
    ON adc_bolsas_relacionadas(bolsa_proceso_id);

CREATE OR REPLACE VIEW oportunidades_activas AS
SELECT p.*
FROM procesos p
WHERE p.es_oportunidad = TRUE
  AND p.ambito_administrativo = 'SI'
  AND COALESCE(LOWER(p.estado), '') NOT IN
      ('finalizado','finalitzado','finalitzat','cancelado','cancel·lado',
       'cancel·lat','desistido','desistit','anulado','anul·lat')
  AND COALESCE(UPPER(p.turno), '') <> 'PROMOCION_INTERNA'
  AND COALESCE(LOWER(p.tipo_proceso), '') NOT IN
      ('promoción interna','promocion interna','libre designación',
       'libre designacion','concurso general de méritos',
       'concurso de méritos para la provisión','concurso de traslados',
       'comisiones de servicio','difícil cobertura',
       'anuncio difícil cobertura','anuncio dificil cobertura',
       'acto único telemático','acto unico telematico',
       'acte unic telematic','acte únic telemàtic');

ALTER TABLE organismos ENABLE ROW LEVEL SECURITY;
ALTER TABLE fuentes ENABLE ROW LEVEL SECURITY;
ALTER TABLE procesos ENABLE ROW LEVEL SECURITY;
ALTER TABLE publicaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE cambios ENABLE ROW LEVEL SECURITY;
ALTER TABLE suscripciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE seguimiento_estado_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE temarios_empleo ENABLE ROW LEVEL SECURITY;
ALTER TABLE temas_empleo ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleo_eventos_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE empleo_envios_notificacion ENABLE ROW LEVEL SECURITY;
ALTER TABLE adc_bolsas_relacionadas ENABLE ROW LEVEL SECURITY;
